package mytix.database.demo;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/** Generate the standalone SQL loader from the same newly authored demo model. No DB access. */
public final class DemoSqlExport {
    private DemoSqlExport() {}

    public static void main(String[] args) throws Exception {
        if (args.length != 1) throw new IllegalArgumentException("Usage: DemoSqlExport <output.sql>");
        DemoDataset data = DemoDataset.prepare(LocalDate.now(ZoneOffset.UTC));
        StringBuilder sql = new StringBuilder("-- Generated by mytix.database.demo.DemoSqlExport; see docs/demo-data.md.\n"
                + "-- Fresh synthetic data, public password MyTixDemo!42; dates relative to UTC load date.\n"
                + "-- Replaces ALL data in the selected MyTix database. Run using mysql batch mode without --force.\n"
                + "SET NAMES utf8mb4;\nSET @mytix_previous_time_zone = @@session.time_zone;\n"
                + "SET time_zone = '+00:00';\nSET @mytix_anchor = UTC_DATE();\nSTART TRANSACTION;\n");
        List<String> reverse = new ArrayList<>(DemoDataset.INSERT_ORDER);
        Collections.reverse(reverse);
        for (String table : reverse) sql.append("DELETE FROM `").append(table).append("`;\n");
        for (String table : DemoDataset.INSERT_ORDER) {
            List<Map<String,Object>> rows = data.tables.get(table);
            if (rows.isEmpty()) continue;
            List<String> columns = new ArrayList<>(rows.get(0).keySet());
            for (int start=0; start<rows.size(); start+=100) {
                sql.append("INSERT INTO `").append(table).append("` (")
                        .append(columns.stream().map(c -> "`"+c+"`").collect(Collectors.joining(",")))
                        .append(") VALUES\n");
                int end = Math.min(start+100,rows.size());
                for (int i=start;i<end;i++) {
                    Map<String,Object> row = rows.get(i);
                    sql.append('(').append(columns.stream().map(c -> literal(row.get(c),data.date))
                            .collect(Collectors.joining(","))).append(i+1==end ? ");\n" : "),\n");
                }
            }
        }
        sql.append("COMMIT;\nSET time_zone = @mytix_previous_time_zone;\n");
        Files.writeString(Path.of(args[0]),sql,StandardCharsets.UTF_8);
        System.out.println("Exported " + data.counts().values().stream().mapToLong(Long::longValue).sum()
                + " rows into " + args[0]);
    }

    private static String literal(Object value,LocalDate anchor) {
        if (value==null) return "NULL";
        if (value instanceof LocalDateTime stamp) {
            return "TIMESTAMP("+literal(stamp.toLocalDate(),anchor)+",'"+stamp.toLocalTime()+"')";
        }
        if (value instanceof LocalDate date) {
            return "DATE_ADD(@mytix_anchor,INTERVAL "+ChronoUnit.DAYS.between(anchor,date)+" DAY)";
        }
        if (value instanceof Number) return value.toString();
        if (value instanceof Boolean flag) return flag ? "1" : "0";
        // UTF-8 hex literals work regardless of NO_BACKSLASH_ESCAPES and preserve every character.
        return "CONVERT(X'"+HexFormat.of().formatHex(value.toString().getBytes(StandardCharsets.UTF_8))+"' USING utf8mb4)";
    }
}
